variables:
  Major: 9
  Minor: 0
  Patch: 0
  BuildConfiguration: Release

name: $(Major).$(Minor).$(Patch).$(rev:r)
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Build Number $(name)
- task: UseDotNet@2
  displayName: 'Use .NET 8.0 sdk'
  inputs:
    packageType: sdk
    version: 9.0.100
    installationPath: $(Agent.ToolsDirectory)/dotnet
- script: echo Started restoring the source code
- task: DotNetCoreCLI@2
  displayName: 'Restoring'
  inputs:
    command: 'restore'
    projects: |
      **/Xunit.Microsoft.DependencyInjection.csproj
      **/examples/Xunit.Microsoft.DependencyInjection.ExampleTests/Xunit.Microsoft.DependencyInjection.ExampleTests.csproj
    feedsToUse: 'select'
- script: echo Started building the source code
- task: DotNetCoreCLI@2
  displayName: 'Building'
  inputs:
    command: 'build'
    projects: |
      **/Xunit.Microsoft.DependencyInjection.csproj
      **/examples/Xunit.Microsoft.DependencyInjection.ExampleTests/Xunit.Microsoft.DependencyInjection.ExampleTests.csproj
    arguments: '--configuration $(BuildConfiguration)'
    
