variables:
  Major: 1
  Minor: 0
  Patch: 0
  BuildConfiguration: Release

name: $(Major).$(Minor).$(Patch).$(rev:r)
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Build Number $(name)
- task: UseDotNet@2
  displayName: 'Use .NET 6.0 sdk'
  inputs:
    packageType: sdk
    version: 6.0.200
    installationPath: $(Agent.ToolsDirectory)/dotnet
- script: echo Started restoring the source code
- task: DotNetCoreCLI@2
  displayName: 'Restoring'
  inputs:
    command: 'restore'
    projects: '**/Xunit.Microsoft.DependencyInjection.csproj'
    feedsToUse: 'select'
- script: echo Started building the source code
- task: DotNetCoreCLI@2
  displayName: 'Building'
  inputs:
    command: 'build'
    projects: '**/Xunit.Microsoft.DependencyInjection.csproj'
    arguments: '--configuration $(BuildConfiguration)'
- task: NuGetCommand@2
  displayName: 'Packing'
  inputs:
    command: 'pack'
    packagesToPack: '**/Xunit.Microsoft.DependencyInjection.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'Build.BuildNumber'
    
