global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using System.Collections.Generic;
global using System.Threading.Tasks;
global using Xunit.Abstractions;
global using Xunit.Microsoft.DependencyInjection.Abstracts;
global using Xunit.Microsoft.DependencyInjection.Attributes;
global using Xunit.Microsoft.DependencyInjection.ExampleTests.Fixtures;
global using Xunit.Microsoft.DependencyInjection.ExampleTests.Services;